apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: quarkus-monitor
  namespace: monitoring # Создаем там же, где Prometheus
  labels:
    release: kube-stack-prometheus
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: quarkus-app # Должно совпадать с меткой вашего Service
  endpoints:
    - port: http # Имя порта в вашем Service (проверьте, что в Service указано name: http)
      path: /q/metrics
      interval: 15s
